spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/sell?characterEncoding=utf-8&useSSL=false
    username: emery
    password: desktop
  jpa:
    show-sql: true
debug: false
server:
  # 根目录
  context-path: /sell
