spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/sell?characterEncoding=utf-8&useSSL=false
    username: emery
    password: desktop
  jpa:
    show-sql: true
  thymeleaf:
    # 开发时禁用缓存
    cache: false
    mode: LEGACYHTML5
debug: true
server:
  # 根目录
  context-path: /sell

